apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newssummariser-fe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: news.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: newssummariser-fe-service
            port:
              number: 80

