apiVersion: v1
kind: Service
metadata:
  name: newssummariser-fe-service
  labels:
    app: newssummariser-fe
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30082  # Access via minikube IP:30082
  selector:
    app: newssummariser-fe

